site_name: Github Actions Workflow with Federated Identity to host App in Azure
nav:
  - "1. Introduction": "index.md"
  - "2. Resource Group": "page2.md"
  - "3. App, SP, Role": "page3.md"
  - "4. Secrets": "page4.md"
  - "5. Workflow": "page5.md"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fernandoroa
    - icon: fontawesome/brands/twitter
      link: https://x.com/FernandoGenome
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fernando-roa-422bb614/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
